# Generated by Django 4.2.16 on 2024-10-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pretensao_salarial', models.FloatField()),
                ('escolaridade', models.CharField(choices=[('EF', 'Ensino fundamental'), ('EM', 'Ensino médio'), ('TE', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('PO', 'Pós / MBA / Mestrado'), ('DO', 'Doutorado')], max_length=2)),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ats_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ats_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('A', 'Até 1.000'), ('B', 'De 1.000 a 2.000'), ('C', 'De 2.000 a 3.000'), ('D', 'Acima de 3.000')], max_length=1)),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.CharField(choices=[('EF', 'Ensino fundamental'), ('EM', 'Ensino médio'), ('TE', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('PO', 'Pós / MBA / Mestrado'), ('DO', 'Doutorado')], max_length=2)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats_manager.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('candidato_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats_manager.candidato')),
            ],
        ),
    ]
