# Generated by Django 4.2.16 on 2024-10-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_manager', '0002_candidato_empresa_vaga_experiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
    ]
