# Generated by Django 4.2.16 on 2024-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_manager', '0004_vaga_candidatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
